// <auto-generated />
using System;
using CodingClub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodingClub.Migrations
{
    [DbContext(typeof(CodingClubContext))]
    [Migration("20200915194100_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("CodingClub.ClubMember", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClubTitle")
                        .HasColumnType("TEXT");

                    b.Property<bool>("DuesPaid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Team")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamsTeamID")
                        .HasColumnType("INTEGER");

                    b.HasKey("MemberID");

                    b.HasIndex("TeamsTeamID");

                    b.ToTable("ClubMember");
                });

            modelBuilder.Entity("CodingClub.Content", b =>
                {
                    b.Property<int>("ContentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentTitle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatorMemberID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullContent")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentID");

                    b.HasIndex("CreatorMemberID");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("CodingClub.Teams", b =>
                {
                    b.Property<int>("TeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProjectDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TeamLeaderMemberID")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeamID");

                    b.HasIndex("TeamLeaderMemberID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("CodingClub.ClubMember", b =>
                {
                    b.HasOne("CodingClub.Teams", null)
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamsTeamID");
                });

            modelBuilder.Entity("CodingClub.Content", b =>
                {
                    b.HasOne("CodingClub.ClubMember", "Creator")
                        .WithMany("CreatedContent")
                        .HasForeignKey("CreatorMemberID");
                });

            modelBuilder.Entity("CodingClub.Teams", b =>
                {
                    b.HasOne("CodingClub.ClubMember", "TeamLeader")
                        .WithMany()
                        .HasForeignKey("TeamLeaderMemberID");
                });
#pragma warning restore 612, 618
        }
    }
}
